openapi: 3.0.0
info:
  title: Bookstore API
  version: 1.0.0
servers:
  - url: https://api.bookstore.com/v1
    description: Production server

paths:
  /products:
    get:
      summary: Получить список книг
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Строка поиска
        - in: query
          name: genre
          schema:
            type: array
            items:
              type: string
          description: Список жанров
        - in: query
          name: page
          schema:
            type: integer
            format: int32
            default: 1
          description: Номер страницы
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
            default: 20
          description: Количество книг на странице
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  total:
                    type: integer
                    description: Общее количество книг
        '400':
          description: Ошибка запроса
  /products/{id}:
    get:
      summary: Получить информацию о книге
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID книги
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Книга не найдена
  /cart:
    get:
      summary: Получить данные корзины
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    put:
      summary: Обновить данные корзины
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        '200':
          description: Успешно обновлено
        '400':
          description: Ошибка обновления
    post:
      summary: Добавить товар в корзину
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                  format: int64
                quantity:
                  type: integer
                  format: int32
      responses:
        '201':
          description: Товар добавлен
        '400':
          description: Ошибка добавления
  /cart/{productId}:
    delete:
      summary: Удалить товар из корзины
      parameters:
        - in: path
          name: productId
          schema:
            type: integer
            format: int64
          required: true
          description: ID товара
      responses:
        '200':
          description: Товар удален
        '404':
          description: Товар не найден
  /order:
    post:
      summary: Создать заказ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Заказ создан
        '400':
          description: Ошибка создания заказа
  /order/{id}:
    get:
      summary: Получить информацию о заказе
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID заказа
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Заказ не найден


components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        author:
          type: string
        genre:
          type: array
          items:
            type: string
        price:
          type: number
          format: float
        description:
          type: string
        imageUrl:
          type: string
        rating:
          type: number
          format: float
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/Review'
    Review:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        text:
          type: string
        rating:
          type: integer
          format: int32
    Cart:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              productId:
                type: integer
                format: int64
              quantity:
                type: integer
                format: int32
              product:
                $ref: '#/components/schemas/Product'
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        total:
          type: number
          format: float
        deliveryMethod:
          type: string
          enum: [courier, pickup]
        paymentMethod:
          type: string
          enum: [card, cash]
        status:
          type: string
          enum: [pending, processing, shipped, delivered]
    OrderItem:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/Product'
        quantity:
          type: integer
          format: int32